CREATE TABLE TO_DO_ITEM (
  SEQ SERIAL PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  CONTENT VARCHAR(3000),
  START_DT DATE NOT NULL,
  COMPLETED BOOLEAN DEFAULT FALSE,
  REG_DT DATE NOT NULL,
  MODI_DT DATE
);